package de.leuphana.ui.view.matchHistory;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import de.leuphana.ui.components.MatchHistoryGrid;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MatchHistoryViewDesign extends VerticalLayout {
	protected Panel searchPanel;
	protected TextField searchField;
	protected Button searchButton;
	protected CheckBox includePast;
	protected MatchHistoryGrid matchHistoryGrid;

	public MatchHistoryViewDesign() {
		Design.read(this);
	}
}
