package de.leuphana.ui.view.summoner;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SummonerViewDesign extends CssLayout {
	protected Panel searchPanel;
	protected TextField searchField;
	protected Button searchButton;
	protected Label linkLabel;
	protected HorizontalLayout label;
	protected Image summonerImage;
	protected Label nameLabel;
	protected Label levelLabel;
	protected Label rankLabel;
	protected Label winsLabel;
	protected Label lossesLabel;
	protected Label leaguePointsLabel;

	public SummonerViewDesign() {
		Design.read(this);
	}
}
