package de.leuphana.ui.view.champion;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ChampionDetailViewDesign extends VerticalLayout {
	protected Image championImage;
	protected Label championNameLabel;
	protected Label attackDamageLabel;
	protected Label armorLabel;
	protected Label hpLabel;
	protected Grid<net.rithms.riot.api.endpoints.static_data.dto.Champion> championDetailGrid;

	public ChampionDetailViewDesign() {
		Design.read(this);
	}
}
